### ISSUE TITLE
How to accelerate the generation?

### ISSUE THREAD

**Issue by ztcintokyo** [facebookresearch/access#15]
Hi
I would like to generate 1M sentences using your ACCESS. However, using generate.py seems slow, I'll appreciate it if you can give me some ideas to accelerate it.
Thank you!

**Comment by louismartin** [comment]
Hi, thanks for your interest!

I am not sure how to speed this up, however here are some ideas that might help.
The generation uses the `fairseq-generate` command in the [`_fairseq_generate`](https://github.com/facebookresearch/access/blob/ede11a0fc4bd3e8542c6e6ff49b677a4e0927cbc/access/fairseq/base.py#L178) function.
* Are you using a GPU? If not, you should definitely use one
* You could lower the beam size [here](https://github.com/facebookresearch/access/blob/ede11a0fc4bd3e8542c6e6ff49b677a4e0927cbc/scripts/generate.py#L31), at the extreme, a beam size of 1 would be much faster at the cost of quality of the simplifications. Maybe you could try lowering it progressively until it's fast enough (8->5->3->1).
* Do you have access to multiple GPUs? AWS? For a relatively low price you could parallelize the simplification by splitting your sentences among multiple GPUs. If you have only one GPU maybe having multiple processes on the same GPU could help.
* The preprocessing step (computing the control ratios) might be distributable as well, so trying to generate using multiple processes can help with this respect.

Good luck,
Best,
Louis

**Comment by louismartin** [comment]
Can you try `CUDA_VISIBLE_DEVICES=0 python -c 'import torch; print(torch.cuda.device_count())'` as per this [issue](https://github.com/pytorch/fairseq/issues/1117)?

**Comment by ztcintokyo** [comment]
I tried CUDA_VISIBLE_DEVICES=3 python -c 'import torch; print(torch.cuda.device_count())' and the output is 1

**Comment by louismartin** [comment]
Hi @ztcintokyo 
I am not sure what is the problem then, maybe you should drop into pdb and check that `use_cuda` is set to `True` [here](https://github.com/louismartin/fairseq/blob/1e30f27b159daced4a7340d0d0d2c590311a6061/generate.py#L60) and check that during the generation, the tensors are indeed on the GPU.

**Comment by ztcintokyo** [comment]
I have solved the problem.
Thank you for your patience!
