### ISSUE TITLE
Typo in the License File

### ISSUE THREAD

**Issue by gmanasi13** [facebookresearch/access#18]
The first line in the license file is missing a 'A'

Current text: ttribution-NonCommercial 4.0 International
Expected text: Attribution-NonCommercial 4.0 International

License file are an important part of source code and should not have errors. This helps developers to correctly reference the license when integrating the source code within their applications.

I will create a pull request for the same.

**Comment by louismartin** [comment]
Thanks for the fix, that's merged!
