### ISSUE TITLE
requirement "torch==1.2.0" unfound

### ISSUE THREAD

**Issue by NicolasMICAUX** [facebookresearch/access#22]
```
ERROR: Could not find a version that satisfies the requirement torch==1.2.0 (from access)
ERROR: No matching distribution found for torch==1.2.0
```
impossible to install a version below 1.4.0 with pip.

**Comment by louismartin** [comment]
Hi thanks for the issue.
Pytorch version was downgraded in PR https://github.com/facebookresearch/access/pull/21 related to issue https://github.com/facebookresearch/access/issues/20.
Let me investigate.

**Comment by louismartin** [comment]
I updated the torch version to 1.4, feel free to reopen if you have other issues.
