### ISSUE TITLE
"https://bitbucket.org/eigen/eigen/get/b2e267dc99d4.zip" unfound

### ISSUE THREAD

**Issue by NicolasMICAUX** [facebookresearch/access#23]
dynet install tries to download "https://bitbucket.org/eigen/eigen/get/b2e267dc99d4.zip" but file does not seem to exist

**Comment by louismartin** [comment]
Hi thanks for the issue,

It seems to be related to https://github.com/clab/dynet/issues/1101
Can you give me more info about which requirement needs to install the dynet package?

**Comment by louismartin** [comment]
Hi @NicolasMICAUX, have you solved the problem?

**Comment by louismartin** [comment]
I'll close this issue for now as it does not seem related to ACCESS, feel free to reopen if you have more comments.

**Comment by NicolasMICAUX** [comment]
I actually didn't used access in the end, but thx for the answer ! (2 months after :(    )
