### ISSUE TITLE
Reversing the results 

### ISSUE THREAD

**Issue by ajay01994** [facebookresearch/access#25]
Hi ,

Thanks for releasing access ,its quite useful . I was wondering if  you could tell me how to reverse the outputs ,meaning that if i give a simple sentence as an input , it should paraphrase it as a complex sentence . Looking forward for your reply 

Regards 

Ajay Sahu

**Comment by louismartin** [comment]
Hi Ajay, thanks for the question!
Sadly you would have to retrain the model from scratch and reverse de complex and simple sides of dataset.
You can do so by downloading the wikilarge dataset, putting the simple sentence as the source and complex sentence as target and use the scripts/train.py script.

**Comment by ajay01994** [comment]
@louismartin  , Thanks for your quick reply , is it possible for you to tell me how much time /hardware was needed to train your original model  ?

**Comment by louismartin** [comment]
Hum I don't remember exactly, I would say one V100 GPU for 1-2 days

**Comment by ajay01994** [comment]
ok, i get it , is it possible for you to create a colab notebook for this repo ? it will help everyone , meanwhile i will  try experimenting with reversing the results .

**Comment by louismartin** [comment]
Hi @ajay01994 unfortunately I cannot create a colab notebook for this repo, but feel free to submit a PR if you want to!
I'm closing this issue but feel free to reopen if you have more questions.
