### ISSUE TITLE
generate.py open too many temporary files

### ISSUE THREAD

**Issue by vanh17** [facebookresearch/access#30]
Is there a way to stop the generate.py to generate too many temporary files? This can be an issue because it is quickly eating up memory in the /tmp directory. Thanks!

**Comment by louismartin** [comment]
Hey @vanh17 , that's a good question.
I think the temporary files might mostly be generated [here](https://github.com/facebookresearch/access/blob/7b61fbf0bad665798d662e0a90d2a0e451367df6/access/simplifiers.py#L63).
The temporary file can probably be deleted at the end of the enclosing function, might be try this as a quick hack?

If you want better simplification models, you can also use the latest [MUSS](https://github.com/facebookresearch/muss).

**Comment by louismartin** [comment]
Hi @vanh17 , any luck with your problem?

**Comment by louismartin** [comment]
Closing for now, feel free to comment or open again if you are still having issues.
