### ISSUE TITLE
Control token values during training

### ISSUE THREAD

**Issue by izaskr** [facebookresearch/access#33]
Hi, I'm going through the preprocessing and training code. I'm wondering where to find the values of control tokens during training, together with the source and target sides. 
Just like the example given in Table 1 of the paper:
```
Source: <NbChars 0.3><LevSim 0.4>He settled in London , devoting himself chiefly to practical teaching .
Target: He teaches in London .
```
Is there a way to access these values during training? Also, what dependency parser did you use for the `DepTreeDepth` token and what are the frequencies for `WordRank` based on (which corpus, WikiLarge or something else)?

**Comment by louismartin** [comment]
Hi, thank you for your issue!
The special tokens are written to text files [here](https://github.com/facebookresearch/access/blob/7b61fbf0bad665798d662e0a90d2a0e451367df6/access/fairseq/main.py#L117).
You can find the resulting text files by browsing in `resources/datasets/` after executing the training code.

At test time they are generated on-the-fly by preprocessors defined [here](https://github.com/facebookresearch/access/blob/main/access/preprocessors.py).

For dependency parsing, we use Spacy ([see this method](https://github.com/facebookresearch/access/blob/7b61fbf0bad665798d662e0a90d2a0e451367df6/access/feature_extraction.py#L54)).

**Comment by izaskr** [comment]
Great, thank you!
