### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by igormis** [facebookresearch/access#5]
I have the authentication problem when I try to clone the repo
Cloning into 'access'... git@github.com: Permission denied (publickey). fatal: Could not read from remote repository.
Could u help me on this

**Comment by louismartin** [comment]
What command did you run exactly?

You can try to clone using https:
`git clone https://github.com/facebookresearch/access.git`

**Comment by igormis** [comment]
Solved,
tnx Louis
