### ISSUE TITLE
fairseq_simplifier in Mem

### ISSUE THREAD

**Issue by igormis** [facebookresearch/access#6]
I am currently using the `generate.py` script in order to paraphrase sentences in a given input file. However, I was wondering is there a way to use the code (fairseq_simplifier) in an API-fashion, that is sentence by sentence, where the best model will be always in RAM so the output will be faster?

**Comment by louismartin** [comment]
Hello Igormis,

Sorry this is not implemented at the time, you would need to adapt code from [fairseq/interactive.py](https://github.com/pytorch/fairseq/blob/master/interactive.py) to do that.

**Comment by igormis** [comment]
OK, tnx. Hope to see this feature in near time... Tnx again
