### ISSUE TITLE
No module named access

### ISSUE THREAD

**Issue by Crista23** [facebookresearch/access#9]
I am trying to run the training script as below, however this gives me an error. How can I fix it?

              python scripts/train.py
              Traceback (most recent call last):
              File "scripts/train.py", line 8, in <module>
              from access.fairseq.main import fairseq_train_and_evaluate
              ModuleNotFoundError: No module named 'access'

**Comment by louismartin** [comment]
Hi @Crista23,
Did you install access by following the README instructions?
```
pip install -e .
```

**Comment by Crista23** [comment]
That was causing the problem indeed, thank you!
